# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input:          GFM
encoding:		  utf-8

# Permalinks
permalink:        /posts/:title

# Setup
title:            DeltaLumin Year 1
url:              research.mylumin.com
baseurl:          /
author:
  name:           Lumin Research
pages_list:
  Work: 'work/index.html'
  Resume: 'about/index.html'
category-list: [] # can expand to include more categories as they are added

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/DeltaInstitute/LuminResearch
name: 			  	Lumin Research

# Plugins
exclude: [vendor]
